### PR TITLE
Load template field inner classes via the classloader that loaded the template

### PR DESCRIPTION
**Pull request by alkemist**
This allows Rocker to be used in environments where the class loader that loaded the Rocker runtime does not load the template/model classes.

One such environment is with Gradle's Continuous Build feature.

### CODE REVIEW

**Comment by alkemist** [comment]
Regarding the change to ConstantPoolMain.java…

The only change is that change to this callsite: https://github.com/alkemist/rocker/blob/1818ecfd001853c3175307bc8c019ed1bd92869b/java6test/src/test/java/com/fizzed/rocker/ConstantPoolMain.java#L52-L52

Everything else is just trimming whitespace on blank lines. I can't work out how to get my editor to stop doing this, in this case.

**Comment by alkemist** [comment]
Thanks for merging!

Do you have any plans as to when the next version with this change will be released?

**Comment by jjlauer** [comment]
Just release v0.12.1 for you.  Thx for the contribution.

**Comment by alkemist** [comment]
Thanks @jjlauer

**Pull request merged**
