### PR TITLE
Travis CI --> GitHub Actions CI

### PR DESCRIPTION
**Pull request by sullis**
Motivation:

https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/

### CODE REVIEW

**Comment by sullis** [comment]
@jjlauer

**Comment by sullis** [comment]
WDYT? @jjlauer

**Comment by sullis** [comment]
WDYT? @jjlauer

**Comment by sullis** [comment]
WDYT? @jjlauer

**Comment by sullis** [comment]
ping @jjlauer

**Comment by nedtwigg** [comment]
FWIW I resisted GitHub Actions for a long time, and finally migrated over a couple months ago, and my experience was that it's just way faster with a way more active ecosystem than Travis or Circle. It would be great for this project to get CI up and the easy-win PR's merged in :)

**Comment by jjlauer** [comment]
Already done awhile ago.  Cleaning up very old PRs.

**Pull request closed without merging**
