### PR TITLE
Make @for work with any Iterable object

### PR DESCRIPTION
**Pull request by bendem**
This change makes the rocker `@for` syntax match the java syntax by accepting any object implementing `Iterable`.

I've added this as a workaround for the `@for` syntax not working with streams (see #40) (passing `stream::iterator` to the template instead of collecting to a list - and thus saving my server from high memory usage), but I'm sure others will appreciate not requiring a `Collection` when all that's used is the `Iterable` interface.

### CODE REVIEW

**Comment by bendem** [comment]
Any news on this?

**Comment by jjlauer** [comment]
Hey @bendem, sorry for missing the original github notification about this PR.  I love the idea of supporting iterable (eventually streams too).  Just a few issues with this PR:

1. We need a unit test for it of something that's Iterable and not a Collection.
2. Iterable could be supported in both Java 8 and Java 6 -- but it seems like you only added support for it in Java 8. So while adding a test for 1), make sure you add it in both the java6 and java8 modules.
3.  What about Rocker iterator support (https://github.com/fizzed/rocker/blob/master/docs/SYNTAX.md#iteration-for)?  That's a key feature and I'm not sure how we support it with streams and/or iterables.  Obviously, `last` is probably the only method that can't be supported on it.  Ideally, the Java compiler would catch that if using an iterable -- vs. something like a runtime exception.

**Comment by bendem** [comment]
All of that makes sense, I'll try and look into it later this week.

**Comment by bendem** [comment]
I have replaced `CollectionForIterator` with `IterableForIterator`. That should cover all cases where rocker was using `Collection` instead of `Iterable` at once. I have not looked into `Stream` support (maybe another time).

**Comment by bendem** [comment]
Is there anything else I can do to make your review easier?

**Comment by jjlauer** [comment]
@bendem This looks good.  Thanks for the contrib.  Will ship it in next release.

**Comment by jjlauer** [comment]
Version 0.23.0 is released with this change.  Will hit maven central in couple hours.

**Comment by bendem** [comment]
Awesome, thanks!

**Pull request merged**
