### PR TITLE
Add an InputStream output

### LINKED ISSUE #93: Implement support for rendering to InputStreamRockerOutput
Hello everyone,

I use rocker to render "into" an InputStream which can be consumed later. I would like to have this feature included in the offical rocker distribution to make reuse simpler and share with the community.

### PR DESCRIPTION
**Pull request by Serranya**
This fixes #93

### CODE REVIEW

**Comment by bendem** [comment]
That's an interesting addition but collecting the array of byte arrays, which sole purpose is to prevent duplicating the template in memory, into a single byte array basically nullifies any performance gain under memory constraints.
Would it be possible to add the `asReadableByteChannel` method to your benchmark? This is the baseline you should hit for the `asInputStream` implementation.

**Comment by Serranya** [comment]
> Would it be possible to add the asReadableByteChannel method to your benchmark?

Yeah I will do that.

> This is the baseline you should hit for the asInputStream implementation.

Im not 100% sure about this. Sometimes an API does require an `InputStream`. So even if it's not as fast I think its an helpfull addition. But I agree that it should be possible to reach a similar performance.

I will add some benchmarks.

**Comment by bendem** [comment]
> > This is the baseline you should hit for the asInputStream implementation.
> 
> Im not 100% sure about this. Sometimes an API does require an `InputStream`. So even if it's not as fast I think its an helpfull addition. But I agree that it should be possible to reach a similar performance.

I'm not saying adding `asInputStream` is not useful, I'm saying the implementation could be as performant as the one of `asReadableByteChannel`.

**Comment by Serranya** [comment]
@bendem 
New results:
```
Benchmark                            (bufferSize)  (numberStrings)  (stringLength)  Mode  Cnt       Score       Error  Units
MyBenchmark.writeAndReadByteArray             256            10000            5000  avgt    9  458174,519 ±  6746,243  us/op
MyBenchmark.writeAndReadByteArray             512            10000            5000  avgt    9  454689,656 ±  7035,497  us/op
MyBenchmark.writeAndReadByteChannel           256            10000            5000  avgt    9  453447,887 ± 18714,178  us/op
MyBenchmark.writeAndReadByteChannel           512            10000            5000  avgt    9  458164,614 ± 30466,220  us/op
MyBenchmark.writeAndReadInputStream           256            10000            5000  avgt    9  476919,442 ± 12638,149  us/op
MyBenchmark.writeAndReadInputStream           512            10000            5000  avgt    9  469053,534 ± 19689,848  us/op
```
So yeah seems like the InputStream is a bit slower.

One could implement a custom `InputStream` class that directly reads from the list of arrays. I think we should open a new Issue for that.

What do you think?

**Comment by bendem** [comment]
Continuing the conversation on the issue instead of the PR

**Pull request merged**
