### PR TITLE
This creates a class loader that includes the classes from the projec…

### PR DESCRIPTION
**Pull request by sphogan**
…t one is working on.

It solves a ClassNotFoundException issued from `Class.forName` which would only get
classes pulled in from the Rocker pom rather than your project pom meaning that
post-processors included with Rocker would work, but not post-processors in your project.

I'm not sure that this is a good way to fix the issue, but it means that post-processors in my project are available to use.

### CODE REVIEW

**Comment by jjlauer** [comment]
Hey Sean,

Out of curiosity what sort of thing are you solving with a post-processor
in your project?  Would love to know what it solves for ya.

Looks like your editor removed a bunch of whitespace which mucked w/ the
diff in github.

I'm also not sure this is the right fix, but I also believe we could create
a unit test for it.  Can you try adding a custom post-processor in the
java6tests module?  I would think that would mimic being a in a project
separate from rocker-core or rocker-compiler and maybe help generate the
error you found.  Then we could validate what you proposed actually does
fix it.

-Joe

**Comment by sphogan** [comment]
Hi!

In terms of what I'm trying to achieve: I like the idea of being able to customize the output without having to fork the code.  For example, being able to configure some default imports to avoid having to write imports for common things.  Likewise, I've been playing around with the idea of putting in a `Map<String, Object>` of argName -> argValue which could be converted into JSON by Jackson.

I'll try creating a unit test and fixing the diff, but it might be a couple days.

**Comment by jjlauer** [comment]
Default imports are an interesting feature, I know I find myself just
wanting java.util.* available all the time.  Maybe worth just making that a
feature by itself.  Perhaps letting you add an array of default imports in
the maven plugin.

Not sure I fully understand your json use.  You convert any template
argument of type Map<String,Object> into a String of json?

We've been finding lots of use internally for inlining java objects into
json directly in the template rendering process.  We've been accomplishing
that by overriding the default template all templates extend from, then
supplying a json() method to all templates that let you include an object
to it.

No rush on the unit test.  Appreciate any contribution!

Thx.

Joe

**Comment by jjlauer** [comment]
One more idea, btw.  Each maven plugin can define extra dependencies
that'll be available when it executes.  You're correct that by default that
means only rocker's dependencies.  However, you can add extra dependencies
for execution.

http://maven.apache.org/guides/mini/guide-maven-classloading.html

Did you try adding your own project as a dependency?  You may run into some
chicken-egg issues -- since the post-processor may not exist yet until it
actually compiles.

**Comment by jshinobi** [comment]
>Out of curiosity what sort of thing are you solving with a post-processor in your project? Would love to know what it solves for ya.
A few notes about our use case. For us post-processors were life savers. 
We are using intellij idea and it has quite good syntax checker for html and javascript.
But if use "@" symbol in javascript templates idea can't recognize it and thinks it is error, and the file and the whole project are marked as error-contained. And there was no workaround. Of course we could disable syntax checker on all *.rocker.html files, but in that case we weren't able to use all powerful features like auto-complete, formatting and so on.
So what we did. It was ok to use @ in javascript strings like this:
```
 var userTimeZone = " @K.getUserTimeZone() ";
 const DEFAULT_ZONE_ID = "@BaseController.DEFAULT_ZONE_ID";
```
The main trouble was that we could not get rid of quotes. And were not able to pass int or arrays from java to js. So here post-processors helped us. We made fake quotes '* *' :
```
...
if (time > '* @Globals.IDLE_TIMEOUT *') {
...
columns: '* @raw(columnsAsJson) *',
...
```
and processor which removes fake quotes(but keep it contents). Now intellij idea thinks it correct syntax, and we able to have "green" project. Many thanks to @jfendler .

**Comment by sphogan** [comment]
I'm going to close this PR. I think adding it as a dependency on the plugin configuration is a better way and that works as long as the post-processor is in a different project.  That avoids the chicken-and-egg issue.

In terms of the JSON: I'm using JAX-RS and want to be able to render JSON or HTML depending on what is requested.

In terms of the JSON: let's say I have a template that has `@args(List<Post> posts)` and a URL `/posts`.  I want to do something like:

```
@Path('/posts')
@GET
public posts getPosts() {
  List<Post> posts = . . .
  return posts.template(posts);
}
```

Then I want to have my `MessageBodyWriter` output either a JSON list of the post objects (using Jackson) or render the HTML template.  With one argument, it's easy enough to just have Jackson serialize it.  With more than one argument, I would likely want it to be a Map<arg-name, arg-value> so that it would become a JSON map.

I haven't gotten that far in my thoughts on this.  From your usage, it sounds like you manually pass an object to be used for JSON?  My thinking was that most of the time I'd want to to use whatever args I'm passing into the template and maybe the addition of a `json` tag to the template would let me specify which args/mappings I wanted in the case that I didn't want all of them.

**Comment by jjlauer** [comment]
Sean,

Cool, sounds like that's a good approach.  Your example reminded me that I
had played around with a Dropwizard/MessageBodyWriter awhile back.  This
may give you some ideas:

https://github.com/jjlauer/dropwizard-rocker

I think you could fairly easily take the rocker model (e.g. the template)
and use it to render w/ Jackson.  Perhaps in the MessageBodyWriter itself
deciding what to do.  The model always extends RockerModel and is really
just a placeholder for arguments.

-Joe

**Pull request closed without merging**
