### PR TITLE
Added @else if support

### PR DESCRIPTION
**Pull request by mreuvers**
Hey @jjlauer 

I have added the support for the else if, added tests and all seems to be fine. 
I also updated the syntax file and mentioned it as available since v0.16.0 (you may need to change that if you decide for another version number).

Could you verify, merge and later on release to maven?

Thanks!
Martijn

### CODE REVIEW

**Comment by jjlauer** [comment]
Hey @mreuvers -- everything looks solid -- great work so far.  However, I'm not sure of the `} @else if {` syntax.  No other control logic requires the `@` symbol in the middle so it'd be good if we could figure out how to get it to work.  Based on the comments in your code, it looks like you initially gave that a try, but couldn't get it to parse?

**Comment by mreuvers** [comment]
Hey @jjlauer 

Yeah, I tried it without `@` first. But since I am not that familiar with the parser/lexer as you are , it indeed failed to compile (well lots of tests started to fail for one thing).

The main difference is that the 'else' branch is dealt with by just "} else {" as lexer part and does not require any pushing to a different mode iirc - after that, the rest is content more or less. The else if (just like `@if` would) requires pushing of the modes, when I initially tried that all things went berserk (as in tests failing a lot). I might have missed something then when I was trying it out of course.

If the lexer/parser could be dealt with properly the current added code should just work the same, maybe you have another idea for this since you know your own code a lot better than me?

**Comment by mreuvers** [comment]
Hey @jjlauer 

Thanks, I will use that as example. I had not tried to define the lexer token like that yet. I will get it done and let you know.

**Comment by mreuvers** [comment]
Hey @jjlauer 

I made the changes, see the last commit (somewhere below my last comment it appears I believe). It should be ready now to be merged and released.

**Comment by jjlauer** [comment]
@mreuvers Excellent work as always.  Will test a bit more on some production code and then will do a release.

**Pull request merged**
